// This file is generated by FlutterFire CLI.
// Replace this file with the output of:
//   flutterfire configure
//
// See README.md for setup instructions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  // ⚠️  IMPORTANT: Replace these placeholder values with your actual
  // Firebase project credentials. Run `flutterfire configure` after adding
  // your google-services.json (Android) and GoogleService-Info.plist (iOS).
  // See README.md for full setup instructions.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4T_-zmZ5k7rTrQ_C7MiOES0anSQOIWdI',
    appId: '1:175322652316:android:208d575b9d6a5e2d9e1759',
    messagingSenderId: '175322652316',
    projectId: 'internshipapp-eaf18',
    storageBucket: 'internshipapp-eaf18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYF-rnLBAKERhWIEL5ZawzvevH_JAJo04',
    appId: '1:175322652316:ios:406639e97e840b2f9e1759',
    messagingSenderId: '175322652316',
    projectId: 'internshipapp-eaf18',
    storageBucket: 'internshipapp-eaf18.firebasestorage.app',
    iosClientId:
        '175322652316-kg2q9d64161mfhdjeduga9ebgmhjn1k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipFinder',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4T_-zmZ5k7rTrQ_C7MiOES0anSQOIWdI',
    appId: '1:175322652316:web:4ac88d5445c26ed49e1759',
    messagingSenderId: '175322652316',
    projectId: 'internshipapp-eaf18',
    authDomain: 'internshipapp-eaf18.firebaseapp.com',
    storageBucket: 'internshipapp-eaf18.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYF-rnLBAKERhWIEL5ZawzvevH_JAJo04',
    appId: '1:175322652316:ios:406639e97e840b2f9e1759',
    messagingSenderId: '175322652316',
    projectId: 'internshipapp-eaf18',
    storageBucket: 'internshipapp-eaf18.firebasestorage.app',
    iosClientId:
        '175322652316-kg2q9d64161mfhdjeduga9ebgmhjn1k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4T_-zmZ5k7rTrQ_C7MiOES0anSQOIWdI',
    appId: '1:175322652316:web:fe521ee4645148999e1759',
    messagingSenderId: '175322652316',
    projectId: 'internshipapp-eaf18',
    authDomain: 'internshipapp-eaf18.firebaseapp.com',
    storageBucket: 'internshipapp-eaf18.firebasestorage.app',
  );
}
